# Site settings
# in the templates available like {{ site.myvariable }}.
title: Tina Photographer
email: tina161090@mail.ru
brand: Фотограф Тина Коломойцева
headline: Студийная съемка, Свадебное фото 
description: Я работаю с профессиональными визажистами и парикмахерами >
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://example.com" # the base hostname & protocol for your site
copyright: 2016 Tina Foto.

# Build settings
markdown: kramdown

# Account ids
snapwidget: 276911

# Contacts
email: contact@tinafoto.net
phone: +1-800-555-2016

# Tracking
# googleAnalitycsID: SM-38933844-2

